name: animations
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  go_router: ^8.0.0
  
dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SpecialElite
      fonts:
        - asset: fonts/SpecialElite-Regular.ttf
